notifications:
  slack:
    rooms:
      secure: TQNq34BiMI+DkjRfRjDczrmXqG7uAnLs4eVWNJPbJb8gEkNKFVbU7qt+rHl90InqN8O4VoQpm/T4iUtrnqt7KepTtVfcasFnwDvOILjl+6z1a3+k5oX15O9Ss8JmYBH4peJ1bIZOS+J7SxG4xRtB8+tFPkBiykA5wMaxeSvbTaZkzmZfs+aWa9VhGX4hJdxDnse9OSxOqVhM7MgagnJ4IDAkqPvqz9fcAv+W6jqtw13EvOENkSBDm240p2p+AkaKK3lhBeMd6+614dJDl99h9SFeWjGGac8gclx/SpKSq6zM9FquUPeN6ECSUWJhdqK6Og/yh6N0VlmQRyB4vBCmBBdW6tvkOqBbrlMqBPG+dZtihE1Zfz876nUZBK6kiVX2sQgobx6nB0R5Qz+PvbdJjSaSqKh2KC4fPBapdfHISwUUOdND8jpauWb+OKuf/QMAls9dYTuWnEtdofis6sIrFOsUzQ5WKsUCWGRbqQFSH0AXZqfgFo8IAqEwhIKqiCVaslPCwdgO9yHVwxwTHegKY7nckqnQ25+3HQ5kjNkqfdiIWqEjuaDWSFtnjK/yauI1RX8erUYzVyeFmk83sHunar21gwB0D5jdLa1VGYQjsyIVBInpDeKb4Qsd5x3fdXad1f5zgS482xi6Y2joDP2fQLhaRrg4ln29xn7cW33LGZw=
services:
- docker
env:
- DOCKER_COMPOSE_VERSION=1.24.1
language: python
python: '3.7'
stages:
- package-deps
- gulp
- build
- deploy
- post-test
jobs:
  include:
  - stage: package-deps
    name: install
    script: npm install
  - stage: gulp
    name: gulp
    script: gulp
  - stage: build
  - name: image-app
    script: make build-apy
  - name: image-nginx
    script: make build-nginx
  - stage: deploy
    script: skip
    before_deploy:
    - cd app/
    deploy:
      provider: heroku
      api_key: "${HEROKU_API_KEY}"
      app: holden-apy
      cleanup: false
      on:
        all_branches: true
  - stage: post-test
    name: newman
    language: node_js
    node_js: 13.2.0
    before_install:
    - "./ci/test_bi.sh"
    install: npm install newman
    before_script: make compose
    script: make travis-nm
    after_script: make decompose
  - name: curl
    before_install:
    - "./ci/test_bi.sh"
    install: sudo apt install -y curl
    before_script: make compose
    script: make travis-curl
    after_script: make decompose
  - name: apache benchmark
    before_install:
    - "./ci/test_bi.sh"
    install: sudo apt install -y apache2-utils
    before_script: make compose
    script: make travis-ab
    after_script: make decompose
