notifications:
  slack:
    rooms:
      secure: nSUPxSqmTkHwieKUM3NdVq3/2A1QpKZj58c3hQIWYtYo0TSgNB9YFKp90ZyLKf2njaU4iC/TDojtiHt91UKdsPDwXNCvE1Lokl753MzzbnEDpAOYTy4y9PZYnzAHsKu17Y1ZS0q6p9LCL3ob+rmaVs59cWp11Dv+Ex/mjKxfMikKUejLH8hiZ6suwahoBm7BgeVTIJX+RoEsvtsu6LXw+WTGxdziulo0jUYcwVubyYiSkjMVCLW/ugzibdQVUoK3N3IK1DCu4uwaQKR3kHcdRV96ZLIJdIsbUncdVtjS1fDVNbI1XzhiAqiiUUHGojtdJc+iF1VEVfEf7XXOW8muVB9G9NOINS8Zw3vgfcYHGh9ionUnL0ZTxPK8LGdvJe5m8u8fPpvQ90tYzgt8CrP5AIEtjUFEc0hE8OG/YjNB8RpgjpoSrL0ms66ylMYC7u9DlJ3wAxawaqCycNs9+NmcCh8OYfsNfWMqnZvks5FtlSry/cdWxCLN5YRscHH7nKHNHsARolCTRkwKm6EJ2oN+unhGo5n7BKpe+DxzDNF3IO2+jJSrmLnj5zvTHUlCGf/sDo1sC/TByW/aT/XDLU0UskhWIj1X/Q8FqX+BGbuxlZ2ZCKXntYWrYzBa+d8cXUrSON19ahHQtxGmBY2oNrziMzoKy1xC5g8S9CivMUPI5bc=

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

language: python
python: "3.7"

stages:
  - build
  - deploy
  - post-test

jobs:
  include:
    - stage: build
      name: install-package-dependencies
      script: npm install
    - name: gulp
      script: gulp
    - name: image-app
      script: make build-apy
    - name: image-nginx
      script: make build-nginx

    - stage: deploy
      script: skip
      before_deploy:
        - cd app/
      deploy:
        provider: heroku
        api_key: ${HEROKU_API_KEY}
        app: holden-apy
        cleanup: false
        on:
          all_branches: true

    - stage: post-test
      name: newman
      language: node_js
      node_js: 13.2.0
      before_install:
        - ./ci/test_bi.sh
      install: npm install newman
      before_script: make compose
      script: make travis-nm
      after_script: make decompose
    - name: curl
      before_install:
        - ./ci/test_bi.sh
      install: sudo apt install -y curl
      before_script: make compose
      script: make travis-curl
      after_script: make decompose
    - name: apache benchmark
      before_install:
        - ./ci/test_bi.sh
      install: sudo apt install -y apache2-utils
      before_script: make compose
      script: make travis-ab
      after_script: make decompose